- name: create ASG lifecycle hook
  ec2_asg_lifecycle_hook:
    region: "{{ region }}"
    profile: "{{ profile|default(omit) }}"
    state: present
    autoscaling_group_name: "{{ asg.name }}"
    lifecycle_hook_name: "{{ asg_lifecycle_hook_name }}"
    transition: autoscaling:EC2_INSTANCE_LAUNCHING
    heartbeat_timeout: 3600
    default_result: ABANDON
  when: asg_lifecycle_hook_name|default()
